// 72 utakmice grupne faze SP 2026
const MATCHES = [
  { id:  1, date: '2026-06-11', home: 'Meksiko',             away: 'Južna Afrika',        group: 'A' },
  { id:  2, date: '2026-06-11', home: 'Južna Koreja',        away: 'Češka',               group: 'A' },
  { id:  3, date: '2026-06-12', home: 'Kanada',              away: 'Bosna i Hercegovina', group: 'B' },
  { id:  4, date: '2026-06-12', home: 'SAD',                 away: 'Paragvaj',            group: 'D' },
  { id:  5, date: '2026-06-13', home: 'Katar',               away: 'Švajcarska',          group: 'B' },
  { id:  6, date: '2026-06-13', home: 'Brazil',              away: 'Maroko',              group: 'C' },
  { id:  7, date: '2026-06-13', home: 'Haiti',               away: 'Škotska',             group: 'C' },
  { id:  8, date: '2026-06-13', home: 'Australija',          away: 'Turska',              group: 'D' },
  { id:  9, date: '2026-06-14', home: 'Nemačka',             away: 'Kirasao',             group: 'E' },
  { id: 10, date: '2026-06-14', home: 'Holandija',           away: 'Japan',               group: 'F' },
  { id: 11, date: '2026-06-14', home: 'Obala Slonovače',     away: 'Ekvador',             group: 'E' },
  { id: 12, date: '2026-06-14', home: 'Švedska',             away: 'Tunis',               group: 'F' },
  { id: 13, date: '2026-06-15', home: 'Španija',             away: 'Zelenortska Ostrva',  group: 'H' },
  { id: 14, date: '2026-06-15', home: 'Belgija',             away: 'Egipat',              group: 'G' },
  { id: 15, date: '2026-06-15', home: 'Saudijska Arabija',   away: 'Urugvaj',             group: 'H' },
  { id: 16, date: '2026-06-15', home: 'Iran',                away: 'Novi Zeland',         group: 'G' },
  { id: 17, date: '2026-06-16', home: 'Francuska',           away: 'Senegal',             group: 'I' },
  { id: 18, date: '2026-06-16', home: 'Irak',                away: 'Norveška',            group: 'I' },
  { id: 19, date: '2026-06-16', home: 'Argentina',           away: 'Alžir',               group: 'J' },
  { id: 20, date: '2026-06-16', home: 'Austrija',            away: 'Jordan',              group: 'J' },
  { id: 21, date: '2026-06-17', home: 'Portugal',            away: 'DR Kongo',            group: 'K' },
  { id: 22, date: '2026-06-17', home: 'Engleska',            away: 'Hrvatska',            group: 'L' },
  { id: 23, date: '2026-06-17', home: 'Gana',                away: 'Panama',              group: 'L' },
  { id: 24, date: '2026-06-17', home: 'Uzbekistan',          away: 'Kolumbija',           group: 'K' },
  { id: 25, date: '2026-06-18', home: 'Češka',               away: 'Južna Afrika',        group: 'A' },
  { id: 26, date: '2026-06-18', home: 'Švajcarska',          away: 'Bosna i Hercegovina', group: 'B' },
  { id: 27, date: '2026-06-18', home: 'Kanada',              away: 'Katar',               group: 'B' },
  { id: 28, date: '2026-06-18', home: 'Meksiko',             away: 'Južna Koreja',        group: 'A' },
  { id: 29, date: '2026-06-19', home: 'SAD',                 away: 'Australija',          group: 'D' },
  { id: 30, date: '2026-06-19', home: 'Škotska',             away: 'Maroko',              group: 'C' },
  { id: 31, date: '2026-06-19', home: 'Brazil',              away: 'Haiti',               group: 'C' },
  { id: 32, date: '2026-06-19', home: 'Turska',              away: 'Paragvaj',            group: 'D' },
  { id: 33, date: '2026-06-20', home: 'Holandija',           away: 'Švedska',             group: 'F' },
  { id: 34, date: '2026-06-20', home: 'Nemačka',             away: 'Obala Slonovače',     group: 'E' },
  { id: 35, date: '2026-06-20', home: 'Ekvador',             away: 'Kirasao',             group: 'E' },
  { id: 36, date: '2026-06-20', home: 'Tunis',               away: 'Japan',               group: 'F' },
  { id: 37, date: '2026-06-21', home: 'Španija',             away: 'Saudijska Arabija',   group: 'H' },
  { id: 38, date: '2026-06-21', home: 'Belgija',             away: 'Iran',                group: 'G' },
  { id: 39, date: '2026-06-21', home: 'Urugvaj',             away: 'Zelenortska Ostrva',  group: 'H' },
  { id: 40, date: '2026-06-21', home: 'Novi Zeland',         away: 'Egipat',              group: 'G' },
  { id: 41, date: '2026-06-22', home: 'Argentina',           away: 'Austrija',            group: 'J' },
  { id: 42, date: '2026-06-22', home: 'Francuska',           away: 'Irak',                group: 'I' },
  { id: 43, date: '2026-06-22', home: 'Norveška',            away: 'Senegal',             group: 'I' },
  { id: 44, date: '2026-06-22', home: 'Jordan',              away: 'Alžir',               group: 'J' },
  { id: 45, date: '2026-06-23', home: 'Portugal',            away: 'Uzbekistan',          group: 'K' },
  { id: 46, date: '2026-06-23', home: 'Engleska',            away: 'Gana',                group: 'L' },
  { id: 47, date: '2026-06-23', home: 'Panama',              away: 'Hrvatska',            group: 'L' },
  { id: 48, date: '2026-06-23', home: 'Kolumbija',           away: 'DR Kongo',            group: 'K' },
  { id: 49, date: '2026-06-24', home: 'Švajcarska',          away: 'Kanada',              group: 'B' },
  { id: 50, date: '2026-06-24', home: 'Bosna i Hercegovina', away: 'Katar',               group: 'B' },
  { id: 51, date: '2026-06-24', home: 'Škotska',             away: 'Brazil',              group: 'C' },
  { id: 52, date: '2026-06-24', home: 'Maroko',              away: 'Haiti',               group: 'C' },
  { id: 53, date: '2026-06-24', home: 'Češka',               away: 'Meksiko',             group: 'A' },
  { id: 54, date: '2026-06-24', home: 'Južna Afrika',        away: 'Južna Koreja',        group: 'A' },
  { id: 55, date: '2026-06-25', home: 'Ekvador',             away: 'Nemačka',             group: 'E' },
  { id: 56, date: '2026-06-25', home: 'Kirasao',             away: 'Obala Slonovače',     group: 'E' },
  { id: 57, date: '2026-06-25', home: 'Japan',               away: 'Švedska',             group: 'F' },
  { id: 58, date: '2026-06-25', home: 'Tunis',               away: 'Holandija',           group: 'F' },
  { id: 59, date: '2026-06-25', home: 'Turska',              away: 'SAD',                 group: 'D' },
  { id: 60, date: '2026-06-25', home: 'Paragvaj',            away: 'Australija',          group: 'D' },
  { id: 61, date: '2026-06-26', home: 'Norveška',            away: 'Francuska',           group: 'I' },
  { id: 62, date: '2026-06-26', home: 'Senegal',             away: 'Irak',                group: 'I' },
  { id: 63, date: '2026-06-26', home: 'Zelenortska Ostrva',  away: 'Saudijska Arabija',   group: 'H' },
  { id: 64, date: '2026-06-26', home: 'Urugvaj',             away: 'Španija',             group: 'H' },
  { id: 65, date: '2026-06-26', home: 'Egipat',              away: 'Iran',                group: 'G' },
  { id: 66, date: '2026-06-26', home: 'Novi Zeland',         away: 'Belgija',             group: 'G' },
  { id: 67, date: '2026-06-27', home: 'Panama',              away: 'Engleska',            group: 'L' },
  { id: 68, date: '2026-06-27', home: 'Hrvatska',            away: 'Gana',                group: 'L' },
  { id: 69, date: '2026-06-27', home: 'Kolumbija',           away: 'Portugal',            group: 'K' },
  { id: 70, date: '2026-06-27', home: 'DR Kongo',            away: 'Uzbekistan',          group: 'K' },
  { id: 71, date: '2026-06-27', home: 'Alžir',               away: 'Austrija',            group: 'J' },
  { id: 72, date: '2026-06-27', home: 'Jordan',              away: 'Argentina',           group: 'J' },
];

const GROUPS = ['A','B','C','D','E','F','G','H','I','J','K','L'];

function formatDate(dateStr) {
  const d = new Date(dateStr);
  return d.toLocaleDateString('sr-RS', { day: '2-digit', month: '2-digit' });
}

function getMatchesByGroup(group) {
  return MATCHES.filter(m => m.group === group);
}
